
  CREATE TABLE "ISIS2304A211910"."CLIENTE" 
   (	"IDUSUARIO" NUMBER(*,0) NOT NULL ENABLE, 
	"PAZYSALVO" CHAR(1 BYTE) NOT NULL ENABLE, 
	"IDHABITACION" NUMBER(*,0), 
	 CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("IDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "PAZYSALVO_CK" CHECK (pazYSalvo = 'T' OR pazYSalvo ='F') ENABLE, 
	 CONSTRAINT "IDUSUARIOCLIENTE_FK" FOREIGN KEY ("IDUSUARIO")
	  REFERENCES "ISIS2304A211910"."USUARIO" ("ID") ENABLE, 
	 CONSTRAINT "IDHABITACIONCLIENTE_FK" FOREIGN KEY ("IDHABITACION")
	  REFERENCES "ISIS2304A211910"."HABITACION" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;