
  CREATE TABLE "ISIS2304A211910"."CONSUMOHABITACIONSERVICIO" 
   (	"IDCONSUMOHABITACION" NUMBER(*,0) NOT NULL ENABLE, 
	"IDSERVICIO" NUMBER(*,0), 
	 CONSTRAINT "CONSUMOHABITACIONSERVICIO_PK" PRIMARY KEY ("IDCONSUMOHABITACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "IDCONSUMCONHAB_FK" FOREIGN KEY ("IDCONSUMOHABITACION")
	  REFERENCES "ISIS2304A211910"."CONSUMOHABITACION" ("ID") ENABLE, 
	 CONSTRAINT "IDSERVICIOCONHAB_FK" FOREIGN KEY ("IDSERVICIO")
	  REFERENCES "ISIS2304A211910"."SERVICIO" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
