
  CREATE TABLE "ISIS2304A211910"."HABITACION" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CAPACIDAD" NUMBER(*,0) NOT NULL ENABLE, 
	"COSTOPORNOCHE" NUMBER NOT NULL ENABLE, 
	"CUENTA" NUMBER NOT NULL ENABLE, 
	"NUMERO" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"IDHOTEL" NUMBER(*,0), 
	"IDPLANCONSUMO" NUMBER(*,0), 
	"IDCONSUMOHABITACION" NUMBER(*,0), 
	"IDTIPOHABITACION" NUMBER(*,0), 
	 CONSTRAINT "HABITACION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "CARACTERISTICASHABITACION_CK" CHECK (capacidad >0 AND costoPorNoche >=0 AND cuenta >= 0) ENABLE, 
	 CONSTRAINT "IDHOTELHABITACION_FK" FOREIGN KEY ("IDHOTEL")
	  REFERENCES "ISIS2304A211910"."HOTEL" ("ID") ENABLE, 
	 CONSTRAINT "IDPLANCONHABITACION_FK" FOREIGN KEY ("IDPLANCONSUMO")
	  REFERENCES "ISIS2304A211910"."PLANCONSUMO" ("ID") ENABLE, 
	 CONSTRAINT "IDCONSPORHABHABITACION_FK" FOREIGN KEY ("IDCONSUMOHABITACION")
	  REFERENCES "ISIS2304A211910"."CONSUMOHABITACION" ("ID") ENABLE, 
	 CONSTRAINT "IDTIPOHABITACIONHAB_FK" FOREIGN KEY ("IDTIPOHABITACION")
	  REFERENCES "ISIS2304A211910"."TIPOHABITACION" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
