
  CREATE TABLE "ISIS2304A211910"."PRODUCTO" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"COSTO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PRODUCTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "CARACTERISTICASPRODUCTO_CK" CHECK (costo>=0) ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
