
  CREATE TABLE "ISIS2304A211910"."PRODUCTOCONSUMOHABITACION" 
   (	"IDPRODUCTO" NUMBER(*,0) NOT NULL ENABLE, 
	"IDCONSUMOHABITACION" NUMBER(*,0), 
	 CONSTRAINT "PRODUCTOCONSUMOHABITACION_PK" PRIMARY KEY ("IDPRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "IDPRODPRODCONHAB_FK" FOREIGN KEY ("IDPRODUCTO")
	  REFERENCES "ISIS2304A211910"."PRODUCTO" ("ID") ENABLE, 
	 CONSTRAINT "IDCONPRODCONHAB_FK" FOREIGN KEY ("IDCONSUMOHABITACION")
	  REFERENCES "ISIS2304A211910"."CONSUMOHABITACION" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
