  CREATE TABLE "ISIS2304A211910"."RESERVASERVICIO" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"HORAINICIO" VARCHAR2(20 BYTE), 
	"DIA" VARCHAR2(20 BYTE), 
	"DURACION" NUMBER(*,0), 
	"LUGAR" VARCHAR2(20 BYTE), 
	"IDCLIENTE" NUMBER(*,0), 
	"IDSERVICIO" NUMBER(*,0), 
	 CONSTRAINT "RESERVASERVICIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "CARACTERISTICASRESERVASERV_CK" CHECK (duracion >0) ENABLE, 
	 CONSTRAINT "IDCLIENTERESERVASERVICIO_FK" FOREIGN KEY ("IDCLIENTE")
	  REFERENCES "ISIS2304A211910"."CLIENTE" ("IDUSUARIO") ENABLE, 
	 CONSTRAINT "IDSERVICIORESERVASERVICIO_FK" FOREIGN KEY ("IDSERVICIO")
	  REFERENCES "ISIS2304A211910"."SERVICIO" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
