  CREATE TABLE "ISIS2304A211910"."RESERVAHABITACION" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"FECHAENTRADA" VARCHAR2(20 BYTE), 
	"FECHASALIDA" VARCHAR2(20 BYTE), 
	"NUMEROPERSONAS" NUMBER(*,0), 
	"IDHOTEL" NUMBER(*,0), 
	"IDCLIENTE" NUMBER(*,0), 
	 CONSTRAINT "RESERVAHABITACION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "CARACTERISTICASRESERVAHAB_CK" CHECK (numeroPersonas>0) ENABLE, 
	 CONSTRAINT "IDHOTELRESERVAHAB_FK" FOREIGN KEY ("IDHOTEL")
	  REFERENCES "ISIS2304A211910"."HOTEL" ("ID") ENABLE, 
	 CONSTRAINT "IDCLIENTERESERVAHAB_FK" FOREIGN KEY ("IDCLIENTE")
	  REFERENCES "ISIS2304A211910"."CLIENTE" ("IDUSUARIO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
