  CREATE TABLE "ISIS2304A211910"."SERVICIO" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(60 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"HORAAPERTURA" VARCHAR2(25 BYTE), 
	"HORACIERRE" VARCHAR2(25 BYTE), 
	"CAPACIDAD" NUMBER(*,0), 
	"COSTO" NUMBER, 
	"COSTOINCLUIDO" CHAR(1 BYTE), 
	"IDHOTEL" NUMBER(*,0), 
	"IDTIPOSERVICIO" NUMBER(*,0), 
	 CONSTRAINT "SERVICIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE, 
	 CONSTRAINT "IDHOTELSERVICIO_FK" FOREIGN KEY ("IDHOTEL")
	  REFERENCES "ISIS2304A211910"."HOTEL" ("ID") ENABLE, 
	 CONSTRAINT "IDTIPOSERVICIOSERVICIO_FK" FOREIGN KEY ("IDTIPOSERVICIO")
	  REFERENCES "ISIS2304A211910"."TIPOSERVICIO" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
